# This file is part of evesso.
# https://github.com/TomNeyland/eve-sso

# Licensed under the TBD license:
# http://www.opensource.org/licenses/TBD-license
# Copyright (c) 2015, Tom Neyland <tcneyland+github@gmail.com>

language: python

python:
    - "2.7"
    - "3.4"
    # - "pypy"

install:
    # install python requirements
    - make setup

script:
    # run tests
    - make test
