# This file is part of evesso.
# https://github.com/TomNeyland/eve-sso

# Licensed under the TBD license:
# http://www.opensource.org/licenses/TBD-license
# Copyright (c) 2015, Tom Neyland <tcneyland+github@gmail.com>

language: python

python:
    - "2.7"
    # - "3.4"
    # - "pypy"

install:
    # install python requirements
    - pip install coveralls # should this be in setup.py
    - make setup
script:
    # run tests
    - make test

notifications:
  webhooks:
    urls:
      - 'https://webhooks.gitter.im/e/511f0dc4470ca3aa1a3f'
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # default: false

after_success:
  - coveralls